insert into capsules (serial, type, status, details) values ('C101', 'Dragon 1.0', 'retired', 'Reentered after three weeks in orbit');
insert into capsules (serial, type, status, details) values ('C102', 'Dragon 1.0', 'retired', 'First Dragon spacecraft');
insert into capsules (serial, type, status, details) values ('C103', 'Dragon 1.0', 'unknown', 'First of twenty missions flown under the CRS1 contract');
insert into capsules (serial, type, status, details) values ('C104', 'Dragon 1.0', 'unknown', null);
insert into capsules (serial, type, status, details) values ('C105', 'Dragon 1.1', 'unknown', 'First Dragon v1.1 capsule');
insert into capsules (serial, type, status, details) values ('C106', 'Dragon 1.1', 'active', 'First Dragon capsule to be reused');
insert into capsules (serial, type, status, details) values ('C107', 'Dragon 1.1', 'unknown', null);
insert into capsules (serial, type, status, details) values ('C108', 'Dragon 1.1', 'active', 'Second Dragon capsule to be reused');
insert into capsules (serial, type, status, details) values ('C109', 'Dragon 1.1', 'destroyed', 'Destroyed on impact after F9 launch failure');
insert into capsules (serial, type, status, details) values ('C110', 'Dragon 1.1', 'active', null);
insert into capsules (serial, type, status, details) values ('C111', 'Dragon 1.1', 'active', null);
insert into capsules (serial, type, status, details) values ('C112', 'Dragon 1.1', 'active', null);
insert into capsules (serial, type, status, details) values ('C113', 'Dragon 1.1', 'active', 'The last newly manufactured Dragon 1');
insert into capsules (serial, type, status, details) values ('C201', 'Dragon 2.0', 'active', 'Will be used for the first D2 flight.');
insert into capsules (serial, type, status, details) values ('C202', 'Dragon 2.0', 'active', 'Capsule used to qualify Dragon 2&#39;s environmental control and life support systems.');
insert into capsules (serial, type, status, details) values ('C203', 'Dragon 2.0', 'active', 'Rumored to be used for Inflight Abort Test after DM-1');
insert into capsules (serial, type, status, details) values ('C204', 'Dragon 2.0', 'active', 'Currently in construction for use in DM-2');
insert into capsules (serial, type, status, details) values ('C205', 'Dragon 2.0', 'active', 'In construction for use in first mission in contract under the CCtCap contract');
