insert into cores (serial, block, status, details, water_landing) values ('Merlin1A', null, 'lost', 'Engine failure at T+33 seconds resulted in loss of vehicle', false);
insert into cores (serial, block, status, details, water_landing) values ('Merlin2A', null, 'lost', 'Successful first-stage burn and transition to second stage, maximal altitude 289 km. Harmonic oscillation at T+5 minutes Premature engine shutdown at T+7 min 30 s. Failed to reach orbit.', false);
insert into cores (serial, block, status, details, water_landing) values ('Merlin1C', null, 'lost', 'Residual stage-1 thrust led to collision between stage 1 and stage 2.', false);
insert into cores (serial, block, status, details, water_landing) values ('Merlin2C', null, 'lost', 'Initially scheduled for 23–25 Sep, carried dummy payload – mass simulator, 165 kg (originally intended to be RazakSAT.', false);
insert into cores (serial, block, status, details, water_landing) values ('Merlin3C', null, 'lost', null, false);
insert into cores (serial, block, status, details, water_landing) values ('B0003', 1, 'lost', 'Stage Expended', false);
insert into cores (serial, block, status, details, water_landing) values ('B0004', 1, 'lost', 'First flight of Dragon', false);
insert into cores (serial, block, status, details, water_landing) values ('B0005', 1, 'lost', null, false);
insert into cores (serial, block, status, details, water_landing) values ('B0006', 1, 'lost', 'Suffered engine out at T+1:19 but primary mission successful', false);
insert into cores (serial, block, status, details, water_landing) values ('B0007', 1, 'lost', null, false);
insert into cores (serial, block, status, details, water_landing) values ('B1003', 1, 'lost', 'First flight of Falcon 9 v1.1 upgrade, first Spacex flight from Vandenberg', true);
insert into cores (serial, block, status, details, water_landing) values ('B1004', 1, 'lost', null, false);
insert into cores (serial, block, status, details, water_landing) values ('B1005', 1, 'lost', null, false);
insert into cores (serial, block, status, details, water_landing) values ('B1006', 1, 'lost', 'Broke up after sucessful water landing', true);
insert into cores (serial, block, status, details, water_landing) values ('B1007', 1, 'lost', 'Broke up after sucessful water landing', true);
insert into cores (serial, block, status, details, water_landing) values ('B1008', 1, 'lost', null, false);
insert into cores (serial, block, status, details, water_landing) values ('B1011', 1, 'lost', null, false);
insert into cores (serial, block, status, details, water_landing) values ('B1010', 1, 'lost', 'Broke up after sucessful water landing', true);
insert into cores (serial, block, status, details, water_landing) values ('B1012', 1, 'lost', 'Destroyed on impact with droneship, grid fin hydraulic fluid depleted', false);
insert into cores (serial, block, status, details, water_landing) values ('B1013', 1, 'lost', 'Broke up after sucessful water landing', true);
insert into cores (serial, block, status, details, water_landing) values ('B1014', 1, 'lost', null, false);
insert into cores (serial, block, status, details, water_landing) values ('B1015', 1, 'lost', 'Destroyed on impact with droneship due to excess lateral velocity - throttle stiction', false);
insert into cores (serial, block, status, details, water_landing) values ('B1016', 1, 'lost', null, false);
insert into cores (serial, block, status, details, water_landing) values ('B1018', 1, 'lost', 'RUD at T + 139s - second stage overpressure event due to defective COPV strut heim joint', false);
insert into cores (serial, block, status, details, water_landing) values ('B1019', 1, 'inactive', 'Retired; permanently displayed at Hawthorne headquarters. ', false);
insert into cores (serial, block, status, details, water_landing) values ('B1017', 1, 'lost', 'Destroyed after drone ship landing due to landing leg failure', false);
insert into cores (serial, block, status, details, water_landing) values ('B1020', 1, 'lost', 'Destroyed on Impact with DroneShip (OCISLY) - Excess Velocity, Possible Fuel Exhaustion', false);
insert into cores (serial, block, status, details, water_landing) values ('B1021', 2, 'inactive', 'Core will be given as a gift to the Cape.  ', false);
insert into cores (serial, block, status, details, water_landing) values ('B1022', 2, 'inactive', 'Removed from active fleet for Δ Qualification Testing. Retired after eight to ten test cycles.  Seemingly scrapped at McGregor.', false);
insert into cores (serial, block, status, details, water_landing) values ('B1023', 2, 'inactive', '*At LZ1 as 2018/02/06 ', false);
insert into cores (serial, block, status, details, water_landing) values ('B1024', 2, 'lost', 'RUD on deck of droneship (OCISLY)', false);
insert into cores (serial, block, status, details, water_landing) values ('B1025', 2, 'inactive', '*At LZ2 as 2018/02/06 ', false);
insert into cores (serial, block, status, details, water_landing) values ('B1026', 2, 'lost', 'Permanently scrapped.  ', false);
insert into cores (serial, block, status, details, water_landing) values ('B1028', 3, 'lost', 'Destroyed on pad September 1 2016 during static fire anomaly.', false);
insert into cores (serial, block, status, details, water_landing) values ('B1029', 3, 'inactive', 'Will be given to KSC Visitors Center. ', false);
insert into cores (serial, block, status, details, water_landing) values ('B1031', 3, 'inactive', 'Mothballed At CCAFS. ', false);
insert into cores (serial, block, status, details, water_landing) values ('B1030', 3, 'lost', 'Stage Expended', false);
insert into cores (serial, block, status, details, water_landing) values ('B1032', 3, 'lost', 'Survived water landing, SpaceX couldn&#39;t tug it back to port, so they hired a company to destroy it.  ', true);
insert into cores (serial, block, status, details, water_landing) values ('B1034', 3, 'lost', 'Stage Expended', false);
insert into cores (serial, block, status, details, water_landing) values ('B1035', 3, 'inactive', 'En-route to Hangar AO', false);
insert into cores (serial, block, status, details, water_landing) values ('B1036', 3, 'lost', 'Broke Up After Successful Water Landing', true);
insert into cores (serial, block, status, details, water_landing) values ('B1037', 3, 'lost', 'Stage Expended', false);
insert into cores (serial, block, status, details, water_landing) values ('B1039', 4, 'lost', 'Stage Expended', false);
insert into cores (serial, block, status, details, water_landing) values ('B1038', 3, 'lost', 'Stage Expended', false);
insert into cores (serial, block, status, details, water_landing) values ('B1040', 4, 'lost', 'Stage Expended', false);
insert into cores (serial, block, status, details, water_landing) values ('B1041', 4, 'lost', 'Stage Expended', false);
insert into cores (serial, block, status, details, water_landing) values ('B1042', 4, 'inactive', 'retired. ', false);
insert into cores (serial, block, status, details, water_landing) values ('B1043', 4, 'lost', 'Stage Expended', false);
insert into cores (serial, block, status, details, water_landing) values ('B1033', 3, 'lost', 'Two of the outer engines didn&#39;t re-ignite for the landing burn, ran out of TEA/TEB igniters. ', false);
insert into cores (serial, block, status, details, water_landing) values ('B1044', 4, 'lost', 'Stage Expended', false);
insert into cores (serial, block, status, details, water_landing) values ('B1045', 4, 'lost', 'Stage Expended', false);
insert into cores (serial, block, status, details, water_landing) values ('B1046', 5, 'unknown', 'Returning to Port of LA aboard JRTI as of Dec 4, 2018. ', false);
insert into cores (serial, block, status, details, water_landing) values ('B1047', 5, 'unknown', 'Landed on OCISLY as of Nov 15, 2018. ', false);
insert into cores (serial, block, status, details, water_landing) values ('B1048', 5, 'unknown', null, false);
insert into cores (serial, block, status, details, water_landing) values ('B1049', 5, 'unknown', 'Landed on JRTI as of Jan 11, 2019. ', false);
insert into cores (serial, block, status, details, water_landing) values ('B1050', 5, 'unknown', 'Towed to Port of Canaveral as of Dec 7, 2018. ', true);
insert into cores (serial, block, status, details, water_landing) values ('B1054', 5, 'lost', 'Stage Expended', false);
insert into cores (serial, block, status, details, water_landing) values ('B1051', 5, 'active', null, false);
insert into cores (serial, block, status, details, water_landing) values ('B1052', 5, 'unknown', 'Finished testing at McGregor as of Sep 28, 2018 ', false);
insert into cores (serial, block, status, details, water_landing) values ('B1053', 5, 'unknown', 'Likely finished testing at McGregor as of Sep 28, 2018 ', false);
insert into cores (serial, block, status, details, water_landing) values ('B1055', 5, 'active', 'Arrived at the Cape for Arabsat-6A launch.', false);
insert into cores (serial, block, status, details, water_landing) values ('B1056', 5, 'active', 'En route to the Cape for Arabsat-6A launch.', false);
insert into cores (serial, block, status, details, water_landing) values ('B1057', 5, 'active', 'Undergoing testing at McGregor.', false);
